from keras import backend as K
import math

class Config:

	def __init__(self):

		self.verbose = True

		self.network = 'resnet50'

		# set it true when you use pretrained weights
		self.Imagenet_pretrained = False

		# setting for data augmentation
		self.use_horizontal_flips = False
		self.use_vertical_flips = False
		self.rot_90 = False

		# anchor box scales 
		# The scales is generated on the resize image
		#self.anchor_box_scales = [128, 256, 512]
		self.anchor_box_scales = [32, 64, 128]

		# anchor box ratios
		self.anchor_box_ratios = [[1, 1], [1./math.sqrt(2), 2./math.sqrt(2)], [2./math.sqrt(2), 1./math.sqrt(2)]]

		# size to resize the smallest side of the image
		self.im_size = 600

		# image channel-wise mean to subtract
		self.img_channel_mean = [103.939, 116.779, 123.68]
		self.img_scaling_factor = 1.0

		# number of ROIs at once
		# 每张图片训练时的roi batch
		# number of regions of interest to be used each image
		self.num_rois = 4

		# stride at the RPN (this depends on the network configuration)
		# 图片到特征图的缩放倍数, 取决于网络结构
		# also remember to modify nn.get_img_output_length function
		self.rpn_stride = 16

		self.balanced_classes = False

		# scaling the stdev
		self.std_scaling = 4.0
		self.classifier_regr_std = [8.0, 8.0, 4.0, 4.0]

		# overlaps for RPN
		# decrese it to allow more positive examples
		self.rpn_min_overlap = 0.3
		self.rpn_max_overlap = 0.5 #0.7

		# config for hard negative mining
		self.hard_mining = False

		# overlaps for classifier ROIs
		self.classifier_min_overlap = 0 # 0.1 for hard negative mining
		self.classifier_max_overlap = 0.5

		# placeholder for the class mapping, automatically generated by the parser
		self.class_mapping = None

		#location of pretrained weights for the base network 
		# weight files can be found at:
		# https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_th_dim_ordering_th_kernels_notop.h5
		# https://github.com/fchollet/deep-learning-models/releases/download/v0.2/resnet50_weights_tf_dim_ordering_tf_kernels_notop.h5

		self.model_path = 'model_frcnn.vgg.hdf5'
